### ISSUE TITLE
TCP is working faster than UDP

### ISSUE THREAD

**Issue by AebadUQ** [antimattercorrade/File_Transfer_TCP_UDP#1]
time taken by file to transfer in tcp is faster than udp . why ?

**Comment by antimattercorrade** [comment]
Hi! @AebadUQ 
The TCP transfer speeds tend to vary by varying the options for Delayed ACK and Nagle Algorithm. Did you run TCP with the above options disabled?
For the basic case, i.e. with Nagle's Algorithm and Delayed ACK enabled, the transfer speed for TCP came out to be faster than UDP on some systems for small buffer sizes of around 1-32 Bytes. But again this was for a very small workload of only five files transferred locally which may not represent real world scenarios. Moreover, linux kernel handles polling and handing over of data for TCP and UDP quite differently thus a more robust setup may be required for testing.
